# Generated by Django 3.2.8 on 2021-10-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converterapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
