# Generated by Django 3.2.8 on 2021-10-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converterapp', '0004_rename_image_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
